[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = [
    {name = "Devank Kolpe", email = "devank1234kolpe@gmail.com"},
]
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.5",
    "networkx>=3.5",
    "psycopg2-binary>=2.9.10",
]
